spring:
  datasource:
    url: jdbc:mysql:///ms_account?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: qwe12356
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/*.xml