package com.servicecomb.springboot.msaccount.dao;


import com.microservice.common.mscommon.bean.msaccount.User;
import org.apache.ibatis.annotations.Mapper;


@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated
     */
    int insertSelective(User record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbggenerated Tue Oct 10 23:21:22 CST 2017
     */
    int deleteByPrimaryKey(Long uId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbggenerated Tue Oct 10 23:21:22 CST 2017
     */
    User selectByPrimaryKey(Long uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbggenerated Tue Oct 10 23:21:22 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbggenerated Tue Oct 10 23:21:22 CST 2017
     */
    int updateByPrimaryKey(User record);
    
    /**
     * 根据传入的参数查询账户信息
     * @param account
     * @return
     */
    User selectUserByAccount(String account);
    
    /**
     * 
     * @param uaccount
     * @return
     */
    User selectUserByuAccount(String uaccount);
    
    /**
     * 
     * @param email
     * @return
     */
    User selectUserByEmail(String email);
    
    /**
     * 
     * @param phone
     * @return
     */
    User selectUserByPhone(String phone);
    
}